
services:
  reverse-proxy:
    volumes:
      # Mount the location of the config file
      - /etc/traefik:/etc/traefik
      # Mount the location of the the certs
      - /cert:/cert
    command:
      ## Traefik is configured by the following commands:
      ## Opt out of sharing usage information
      - --global.sendAnonymousUsage=false
      ## Log 
      - --log.level=ERROR 
      - --log.filePath=/var/log/traefik/traefik.log
      - --log.format=common
      ## Access log 
      - --accesslog=true
      - --accesslog.filepath=/var/log/traefik/access.log
      - --accesslog.format=common
      ## Provider 
      - --providers.docker=true 
      - --providers.docker.exposedbydefault=false 
      - --providers.file.directory=/etc/traefik
      - --providers.file.watch=true
      ## Entrypoints 
      - --entrypoints.web.address=:80 
      - --entrypoints.websecure.address=:443 
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
      ## Certificates
      - --certificatesresolvers.prodcertresolver.acme.httpchallenge=true 
      - --certificatesresolvers.prodcertresolver.acme.email=ed@webnunez.com
      - --certificatesresolvers.prodcertresolver.acme.storage=/cert/acme.json 
      - --certificatesresolvers.prodcertresolver.acme.httpchallenge.entrypoint=web 
      ## API Settings 
      - --api.insecure=false 
      - --api.dashboard=false 
      - --api.debug=false 